spring:
  datasource:
    username: postgres
    password: gomeloboy8394
    url: jdbc:postgresql://localhost:5434/schedule_of_students
    driver-class-name: org.postgresql.Driver

  # V(version)__description.sql
  flyway:
    baseline-on-migrate: true